spring.application.name=controle-eventos
# Configuração de Conexão com o Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/controle_eventos_db
spring.datasource.username=postgres
spring.datasource.password=Data@2025

# Configuração do JPA (para criar as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true